Add section with ng add command to install tailwind into Angular project
tailwindlabs/tailwindcss.com pull request #639
Opened 2020-11-30 00:48 UTC by raisiqueira

Add section to Angular guide to install tailwind with `ng add` command to optimize developer time 😄.

2020-12-16 03:45 UTC, simonswiss commented
Hey!

I have fixed the merge conflicts in this branch. For now I have put your copy (slightly edited) at the top of the file, but we need to figure out _where_ this copy would fit best, it's there as a placeholder for now.

Adding [WIP] to the PR title until we land on a solution that can be merged.

We're doing some thinking around places where there is a "fork in the road" in the guide at some point, where there are two possible decisions one could make. That's the case here, with using the `ng add` command vs doing it manually.

2020-12-16 12:45 UTC, raisiqueira commented
Hi, @simonswiss. I think that at the top is the best posistion for `ng add` command.

2021-01-16 12:11 UTC, vltansky requested changes

2021-01-16 12:11 UTC, vltansky commented on src/pages/docs/guides/angular.mdx
> +This command will be install `tailwindcss`, `postcss`, `autoprefixer`, `postcss-loader` and `@angular-builders/custom-webpack`. Will also create `webpack.config.js` and `tailwind.config.js` files.
`@ngneat/tailwind` no longer installing all those plugins, but only `tailwindcss`, `@angular-builders/custom-webpack` and `postcss` (will be removed soon as Angular already support PostCSS 8)

2021-01-29 17:52 UTC, adamwathan commented
Hey thanks for this! This is a bit too much work for us to review and fine-tune on our usual GitHub clean up schedule and needs to be schedule into our normal project calendar to properly process, so it may be several weeks before we get a chance to address this but leaving it open as we do intend to work through this one.

2021-01-29 18:01 UTC, raisiqueira commented
Hi, @adamhopkinson. No problem, i undestand the situation.

2021-01-29 18:25 UTC, adamhopkinson commented
I think the above ping should have been to @adamwathan, not me!

2021-05-24 14:01 UTC, adamwathan commented
Hey thanks for this! We've removed the Angular guide from the repo since it was never properly finished/published, so unfortunately these changes no longer have a home. Hopefully have a chance to do a proper Angular guide in the future. I think some of this stuff has changed too since Angular added more official support for Tailwind recently?

Either way would definitely be open to a PR adding a guide for installing with Angular using the most up to date instructions, and following the conventions from our other guides. We'll get to making one ourselves eventually I hope but if someone else was able to put one together that matched the existing ones in structure and tone that would be great too.

2021-05-24 14:01 UTC, closed without merging